version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.morandizzi.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer.tls.domains[0].main=portainer.morandizzi.com"
      # Edge
      #- "traefik.http.routers.portainer-edge.rule=PathPrefix(`/portainer-edge`)"
      #- "traefik.http.routers.portainer-edge.entrypoints=web"
      #- "traefik.http.services.portainer-edge.loadbalancer.server.port=8000"
      #- "traefik.http.routers.portainer-edge.service=portainer-edge"


volumes:
  portainer_data:

networks: 
  default: 
    external: 
      name: traefik-network 
