name: Deploy Portainer Workflow

on:
  workflow_dispatch:

jobs:
  deploy-traefik:
    uses: artur094/workflows/.github/workflows/docker-deploy.yml@main
    with:
      LABELS: "['native', 'raspberry', 'deploy']"
      DOCKER_COMPOSE_FILE: traefik/docker-compose.yml
      PROJECT_NAME: traefik
      ENVIRONMENT: production
      IMAGE_NAMES: "{}"
    secrets: inherit